name: HTML Validation

on:
  push:
    branches: [ main, testing ]
  pull_request:
    branches: [ main, testing ]

jobs:
  html_validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate HTML files in web/
      run: |
        curl -L -o vnu.jar https://github.com/validator/validator/releases/download/latest/vnu.jar
        java -jar vnu.jar --errors-only web/