name: Python Unit Tests and Docs

on:
  push:
    branches: [ main, testing ]
  pull_request:
    branches: [ main, testing ]

jobs:
  test_and_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        activate-environment: photosift
        auto-activate: false

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests -p "*_test.py"

    - name: Install Sphinx and extensions
      run: |
        pip install sphinx sphinx-autodoc-typehints

    - name: Ensure docs/conf.py exists
      run: |
        if [ ! -f docs/conf.py ]; then
          sphinx-quickstart docs -q --project "PhotoSIFT" --author "Group11" --ext-autodoc
        fi

    - name: Generate API docs
      run: |
        sphinx-apidoc -o docs/api . --force --no-toc --separate

    - name: Add autodoc members to API rst files
      run: |
        for f in docs/api/*.rst; do
          base=$(basename "$f" .rst)
          if [ "$base" != "modules" ] && [ "$base" != "index" ]; then
            echo -e "\n.. automodule:: $base\n   :members:\n   :undoc-members:\n   :show-inheritance:\n" >> "$f"
          fi
        done

    - name: Update API index.rst
      run: |
        echo "PhotoSIFT API Reference\n=======================\n\n.. toctree::\n   :maxdepth: 2\n" > docs/api/index.rst
        for f in docs/api/*.rst; do
          base=$(basename "$f" .rst)
          if [ "$base" != "index" ]; then
            echo "   $base" >> docs/api/index.rst
          fi
        done

    - name: Create top-level index.rst
      run: |
        cat > docs/index.rst << 'EOF'
        Welcome to PhotoSIFT’s Documentation
        ====================================

        Overview
        --------
        PhotoSIFT is a tool for [your project description here].  
        This documentation contains guides, references, and an API overview.

        Contents
        --------
        .. toctree::
           :maxdepth: 2
           :caption: Documentation

           api/index
        EOF

    - name: Build HTML docs
      run: |
        sphinx-build -b html docs docs/_build/html

    - name: Deploy docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build
        publish_branch: gh-pages